name: Example workflow using Snyk
on: 
  push:
  workflow_dispatch:
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
    #  - name: Setup JDK 17
     #   uses: actions/setup-java@v4
     #   with:
     #     distribution: 'temurin' # See 'Supported distributions' for available options
     #     java-version: '17'
     #     cache: maven
     # - name: Maven Build install
      #  run: mvn -B package --file pom.xml
      #- name: Show java
     #   run: |
     #    echo $JAVA_HOME
     #    echo $PATH
      #   java -version 
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven-3-jdk-17@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
